#!/usr/bin/with-contenv bash

echo '
******************************************************
******************************************************
*                                                    *
*                                                    *
*             This image is deprecated.              *
*      We will not offer support for this image      *
*             and it will not be updated.            *
*                                                    *
*                                                    *
******************************************************
******************************************************

We recommend switching to an alternative bouncer such as
https://github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin/


******************************************************
******************************************************'
