#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ -z "${GIN_MODE}" ]]; then
  export GIN_MODE=release
fi

exec \
    s6-notifyoncheck -d -n 300 -w 1000 \
      s6-setuidgid abc /app/bouncer
