name: Check for update and release

on:
  workflow_dispatch:
  schedule:
    - cron:  '45 1 * * *'

jobs:
  call-workflow:
    uses: thespad/actions/.github/workflows/check-and-release.yml@v8.0.3
    with:
      repo_owner: thespad
      app_name: "traefik-crowdsec-bouncer"
      release_type: "github"
      release_url: "https://api.github.com/repos/thespad/traefik-crowdsec-bouncer"
      dockerhub_user: "thespad"
    secrets:
      repo_scoped_token: ${{ secrets.repo_scoped_token }}
      dockerhub_password: ${{ secrets.docker_password }}
